# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f531059c22366a3ba52a64362ee1e556cd059d9d8d94bb00bdc2e4da400261f27f0cf34876b1d91da2e5285a0f9da970a1d88481414554ec053b45bd877773

test:
  secret_key_base: 8245aeaa641077d3edbcadb16a3305d1aba3e6099e8e1e37fdc326d6c1e2fced2b7ebce4212f355357a38144a6c0a0e2605a1344a16a7bb25df151184f0ea4c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
